### ISSUE TITLE
Create a Shipping Value Object

### ISSUE THREAD

**Issue by Aerendir** [Aerendir/component-value-objects#27]
It has a Recipient, a Street, a note, a PhoneNumber, an Email.

**Comment by peter279k** [comment]
@Aerendir, can you explain more details about implementing this?

Thanks.

**Comment by Aerendir** [comment]
@peter279k , I've not more detils to provide.

Reading again my first comment, maybe the "street" field should be changed into "address" field.

So, the Email field, should use an Email immutable object; PhoneNumber the same, Recipient is another object with a Name, a Second Name and a Last name at least, Adress is another immutable object.

For the moment I will not work on this: maybe you would like to?
